name: 'Jupyter CI'
on:
  push:
jobs:
  build-docker-artifacts:
    needs: [ unit-test ]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'main')
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15.x'

      - uses: actions/checkout@v1

      - name: Docker Build
        run: docker build -t jupyter:latest .

      - name: Docker Tag Latest
        run: docker tag jupyter:latest fidelissauro/jupyter-laboratory:latest

      - name: Docker Tag Latest Release
        run: | 
          TAG=$(git describe --tags --abbrev=0)
          docker tag jupyter:latest  fidelissauro/jupyter-laboratory:latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Docker Push Latest
        run: docker push fidelissauro/jupyter-laboratory:latest

      - name: Docker Push Release Tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          docker push fidelissauro/jupyter-laboratory:latest:$TAG